# Generated by Django 5.2 on 2025-05-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='itens',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
